name: CI

on:
  push:
  pull_request:

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting of sonarcloud
          fetch-depth: 0
    - run: npm ci

    - run: npm run build

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUDTOKEN }}
      with:
        projectBaseDir: ${{ github.workspace }}

    - name: run eslint
      run: npx eslint src --ext .ts -f @microsoft/eslint-formatter-sarif -o results.sarif

    - name: Upload lint results (SARIF)
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: azure-boards-rewrite-links.sarif
      if: always()
